language: rust
sudo: true
before_install:
  - yes | sudo add-apt-repository ppa:ricotz/testing
  - sudo apt-get update
install:
  - sudo apt-get install libgtk-3-dev
script:
  - rustc --version
  - mkdir .cargo
  - echo 'paths = ["."]' > .cargo/config
  - git clone --depth 1 https://github.com/rust-gnome/examples _test
  - cd _test
  - cargo build
  - cd ..
  - cargo doc
