[options]
girs_dir = "gir-files"
library = "Pango"
version = "1.0"
target_path = "."
work_mode = "normal"
generate_safety_asserts = false
min_cfg_version = "1.30"

generate = [
    "Pango.Alignment",
    "Pango.BidiType",
    "Pango.Context",
    "Pango.Direction",
    "Pango.EllipsizeMode",
    "Pango.FontMask",
    "Pango.Gravity",
    "Pango.GravityHint",
    "Pango.LayoutIter",
    "Pango.LayoutLine",
    "Pango.Script",
    "Pango.Stretch",
    "Pango.Style",
    "Pango.Variant",
    "Pango.Weight",
    "Pango.WrapMode",
]

manual = [
    "Pango.FontDescription",
    "Pango.Rectangle",
]

[[object]]
name = "Pango.FontMap"
status = "generate"
trait = true

[[object]]
name = "Pango.Layout"
status = "generate"
    [[object.function]]
    name = "xy_to_index"
        [object.function.return]
        nullable = false
