[options]
girs_dir = "gir-files"
library = "Pango"
version = "1.0"
target_path = "."
work_mode = "normal"
generate_safety_asserts = false
min_cfg_version = "1.30"

generate = [
    "Pango.Alignment",
    "Pango.Attribute",
    "Pango.AttrType",
    "Pango.BidiType",
    "Pango.Color",
    "Pango.Context",
    "Pango.Coverage",
    "Pango.CoverageLevel",
    "Pango.Direction",
    "Pango.EllipsizeMode",
    "Pango.FontFace",
    "Pango.FontFamily",
    "Pango.FontMap",
    "Pango.FontMask",
    "Pango.Gravity",
    "Pango.GravityHint",
    "Pango.Glyph",
    "Pango.GlyphItem",
    "Pango.GlyphString",
    "Pango.LayoutIter",
    "Pango.LayoutLine",
    "Pango.LayoutRun",
    "Pango.Matrix",
    "Pango.Renderer",
    "Pango.RenderPart",
    "Pango.Script",
    "Pango.Stretch",
    "Pango.Style",
    "Pango.Underline",
    "Pango.Variant",
    "Pango.Weight",
    "Pango.WrapMode",
]

manual = [
    "Pango.AttrClass",
    "Pango.Rectangle",
]

[[object]]
name = "Pango.*"
status = "generate"
    [[object.function]]
    name = "extents_to_pixels"
        [[object.function.parameter]]
        pattern = ".+"
        const = true
    [[object.function]]
    name = "get_mirror_char"
    #out param
    ignore = true
    [[object.function]]
    name = "log2vis_get_embedding_levels"
    #out param
    ignore = true

[[object]]
name = "Pango.FontDescription"
status = "generate"
    [[object.function]]
    name = "from_string"
        [object.function.return]
        nullable = false
    [[object.function]]
    name = "set_family_static"
    ignore = true
    [[object.function]]
    name = "copy_static"
    ignore = true
    [[object.function]]
    name = "merge_static"
    ignore = true

[[object]]
name = "Pango.Font"
status = "generate"
    [[object.function]]
    name = "descriptions_free"
    ignore = true

[[object]]
name = "Pango.Layout"
status = "generate"
    [[object.function]]
    name = "xy_to_index"
        [object.function.return]
        nullable = false
