[package]
name = "pango-sys"
version = "0.1.0"
authors = ["The Rust-GNOME Project Developers"]
build = "build.rs"
links = "pango"

description = "FFI bindings to Pango"
repository = "https://github.com/rust-gnome/pango"
license = "MIT"

[dependencies]
libc = "0.1"

[build-dependencies]
pkg-config = "0.3"

[dependencies.glib-sys]
git = "https://github.com/rust-gnome/glib.git"